version: '3'

services:
  postgres:
    image: 'postgres'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment: 
      POSTGRES_DB: 'postgres'
      POSTGRES_PASSWORD: password

  app:
    depends_on:
      - 'postgres'
    build: .
    command: bash -c "rm -f tmp/pids/server.pid || true && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - '3000:3000'
    volumes:
      - '.:/sistema_saude'
volumes:
  postgres: