default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  user: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sistema_saude_development

test:
  <<: *default
  database: sistema_saude_test

production:
  <<: *default
  database: sistema_saude_production